version: '2'
services:
    yahoo:
        build: ./yahoo
        environment:
        - YAHOO_CLIENT_ID=$YAHOO_CLIENT_ID
        - YAHOO_CLIENT_SECRET=$YAHOO_CLIENT_SECRET
        volumes:
        - "./yahoo:/yahoo"
        #command: python -u yahoo.py 
        command: tail -F anything 
