version: '2'
services:
    tethys:
        build: ./
        volumes:
        - "./:/tethys"
        command: tail -F anything

    yahoo:
        build: ./yahoo
        environment:
        - YAHOO_CLIENT_ID=$YAHOO_CLIENT_ID
        - YAHOO_CLIENT_SECRET=$YAHOO_CLIENT_SECRET
        volumes:
        - "./yahoo:/yahoo"
        command: tail -F anything
